name = "CirculantAttention"
uuid = "84d5bf51-c9fe-456b-b992-3a1345f8cdeb"
authors = ["nikopj and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
